name: "NexxonTech Hub Build and Deploy"
on:
  pull_request:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v30
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}-${{ hashFiles('**/*.lock') }}
          restore-prefixes-first-match: |
            cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}
            cache-${{ matrix.os }}
      - name: Build the Site
        run: nix build
      - name: Get the Site Artifacts
        run: mkdir -p nexxontech_hub && cp -r result/* nexxontech_hub/
      - name: Upload the Site Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nexxontech_hub
          path: nexxontech_hub/
          retention-days: 30
      - name: Upload the Site for GH Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: nexxontech_hub/
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4